In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_excel(r"D:\Jupyter\RESUME PROJECTS\CARS RESALE\car.xlsx")
df

,brand,model,transmission,age,fuel,price,mileage,power,seats
0,18,244,1,4,1,1231000.0,19.01,4.496471,5
1,10,263,1,6,4,786000.0,19.01,4.496471,5
2,31,123,1,2,1,1489000.0,19.01,4.496471,5
3,9,55,0,1,4,1227000.0,19.01,4.496471,5
4,8,82,1,3,1,887000.0,19.01,4.496471,5
...,...,...,...,...,...,...,...,...,...
32009,5,199,1,6,4,292000.0,19.01,4.496471,5
32010,32,295,1,6,4,534000.0,19.01,4.496471,5
32011,33,25,1,8,4,424000.0,19.01,4.496471,5
32012,10,120,0,5,4,685000.0,19.01,4.496471,5
32013,31,247,1,2,4,392000.0,19.01,4.496471,5

In [3]:
# Separate the features (X) and target variable (y)
X = df.drop('price', axis=1)
y = df['price']

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=32)

In [5]:
 #4
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train,y_train)

print('intercept:',model.intercept_)
print('coefficients:',model.coef_)


# prediction on train data
ypred_train = model.predict(X_train)

# evaluation on train data
from sklearn.metrics import r2_score
print("train r2:",r2_score(y_train,ypred_train))

#cross validation on train data
from sklearn.model_selection import cross_val_score
print('crossvalidationscore:',cross_val_score(model,X_train,y_train,cv=5).mean())

# predict on test data
ypred_test = model.predict(X_test)

from sklearn.metrics import r2_score
print('testr2:',r2_score(y_test,ypred_test))

intercept: -4133534.9837858328
coefficients: [-1.62170948e+03 -2.10283990e+02 -3.32643051e+05 -4.71600421e+04
 -6.62712088e+04 -9.44023157e+03  1.31554435e+06 -1.93154089e+04]
train r2: 0.5889727798174165
crossvalidationscore: 0.5885910581188296
testr2: 0.5713772705454285

In [6]:
from sklearn.model_selection import GridSearchCV

# model
from sklearn.linear_model import Lasso
estimator = Lasso()

# parameters and values

param_grid = {'alpha':list(range(1,30))}

# identifying the best value of the parameter within given values for the given data

model_hp = GridSearchCV(estimator,param_grid,cv=5,scoring='r2')

model_hp.fit(X_train,y_train)

model_hp.best_params_

{'alpha': 23}

In [7]:
from sklearn.linear_model import Lasso
lasso_best = Lasso(alpha=23)
lasso_best.fit(X_train,y_train)

print('intercept:',lasso_best.intercept_)
print('coefficients:',lasso_best.coef_)

intercept: -4131972.7027862924
coefficients: [-1.62396423e+03 -2.10307650e+02 -3.32597959e+05 -4.71616852e+04
 -6.62790428e+04 -9.45291998e+03  1.31519565e+06 -1.92563701e+04]

In [8]:
# prediction and evaluation on train data
ypred_train = lasso_best.predict(X_train)

from sklearn.metrics import r2_score
print('train r2:',r2_score(y_train,ypred_train))

from sklearn.model_selection import cross_val_score
print('cvscore:',cross_val_score(lasso_best,X_train,y_train,cv=5).mean())

# prediction and evaluation on test data

ypred_test = lasso_best.predict(X_test)
print('testr2;',r2_score(y_test,ypred_test))

train r2: 0.5889727599886403
cvscore: 0.5885912061303392
testr2; 0.5713873376824762