In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_excel(r"D:\Jupyter\RESUME PROJECTS\CARS RESALE\car.xlsx")
df

,brand,model,transmission,age,fuel,price,mileage,power,seats
0,18,244,1,4,1,1231000.0,19.01,4.496471,5
1,10,263,1,6,4,786000.0,19.01,4.496471,5
2,31,123,1,2,1,1489000.0,19.01,4.496471,5
3,9,55,0,1,4,1227000.0,19.01,4.496471,5
4,8,82,1,3,1,887000.0,19.01,4.496471,5
...,...,...,...,...,...,...,...,...,...
32009,5,199,1,6,4,292000.0,19.01,4.496471,5
32010,32,295,1,6,4,534000.0,19.01,4.496471,5
32011,33,25,1,8,4,424000.0,19.01,4.496471,5
32012,10,120,0,5,4,685000.0,19.01,4.496471,5
32013,31,247,1,2,4,392000.0,19.01,4.496471,5

In [3]:
# Separate the features (X) and target variable (y)
X = df.drop('price', axis=1)
y = df['price']

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=32)

In [5]:
 #4
from sklearn.preprocessing import PolynomialFeatures
polynomial_converter = PolynomialFeatures(degree=2,include_bias=False)
X_train_poly = pd.DataFrame(polynomial_converter.fit_transform(X_train))
X_test_poly = pd.DataFrame(polynomial_converter.fit_transform(X_test))

from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train_poly,y_train)

print(model.intercept_)
print(model.coef_)


from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
from sklearn.model_selection import cross_val_score

#6
ypred_train = model.predict(X_train_poly)
ypred_test = model.predict(X_test_poly)
#7
print('trainr2:',r2_score(y_train,ypred_train))
print('cv:',cross_val_score(model,X_train_poly,y_train,cv=5,scoring='r2').mean())
print('Test r2:',r2_score(y_test, ypred_test))

8845162.943580108
[ 3.50060525e+04  1.00125326e+04  1.76938182e+06  2.81324514e+05
  3.68532950e+04 -1.04521389e+05 -4.27191972e+06 -1.05299466e+06
 -2.21583342e+02 -3.60489391e+01  6.80765085e+03 -1.81842016e+01
 -8.57650117e+02 -3.41852417e+02 -1.94004236e+03 -1.94782765e+03
 -4.22421322e+00 -1.42159665e+02 -7.01660290e+00 -6.60974894e+01
 -3.96008981e+01 -9.12584019e+02 -5.56647825e+02  1.76938182e+06
  3.20292610e+04  3.73664409e+04 -1.81405829e+04 -9.01174090e+05
  5.95075835e+04  4.82816379e+02  4.78415641e+03  1.35811193e+03
 -1.04809978e+05  1.26947629e+04 -4.31600831e+04  9.80622960e+03
 -3.07110828e+04  7.81268241e+03  1.56173871e+03 -8.14849072e+03
  1.41590555e+04  7.68583648e+05  3.95248112e+04  4.69277303e+04]
trainr2: 0.7583724611475917
cv: 0.7557543449300718
Test r2: 0.7308213321438874

In [6]:
from sklearn.preprocessing import PolynomialFeatures
polynomial_converter = PolynomialFeatures(degree=3,include_bias=False)
X_train_poly = pd.DataFrame(polynomial_converter.fit_transform(X_train))
X_test_poly = pd.DataFrame(polynomial_converter.fit_transform(X_test))

from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train_poly,y_train)

print(model.intercept_)
print(model.coef_)


from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
from sklearn.model_selection import cross_val_score

#6
ypred_train = model.predict(X_train_poly)
ypred_test = model.predict(X_test_poly)
#7
print('trainr2:',r2_score(y_train,ypred_train))
print('cv:',cross_val_score(model,X_train_poly,y_train,cv=5,scoring='r2').mean())
print('Test r2:',r2_score(y_test, ypred_test))

70198931.68228069
[ 1.01072444e+05  2.29726941e+03 -1.83868771e+07 -1.72985334e+06
  5.96180922e+05 -1.36245417e+06 -3.83318440e+07  9.74190332e+06
  1.39069695e+04  1.08065404e+01  5.66528639e+04 -1.93265889e+04
  1.43296319e+04 -6.22493846e+03  3.80076086e+04 -1.25896700e+05
  8.47149077e+01 -7.10645648e+03 -1.19317962e+03 -3.34647999e+03
 -1.85219335e+03  3.48725075e+03  3.00995388e+03 -1.83868737e+07
 -1.15458808e+05  3.42026522e+05  4.49965050e+05  9.52731975e+06
  8.42713397e+05 -5.88725840e+02  8.98469896e+04  2.32185366e+04
  5.13325668e+05  2.43626942e+05 -6.86102780e+05 -2.99903053e+04
  1.51409258e+06 -1.00225758e+06  2.57644887e+03  4.55627886e+05
 -1.10135253e+04  6.11504480e+06 -2.78106600e+06 -5.67917882e+05
 -2.24018393e+01 -2.57850636e+00 -5.88073147e+02 -1.27293431e+00
  3.98639104e+01 -1.36917527e+02 -2.01240937e+03 -4.77013582e+01
 -8.91906433e-02  1.64388947e+01  4.32833173e+00  1.42707050e+00
  9.22429578e+00  5.34012025e+01 -7.27928095e+01  5.66525911e+04
 -3.50291135e+02 -2.37427775e+03 -2.22320813e+03 -1.14246140e+04
  2.12396378e+03  7.41659494e+01  3.40048405e+02  3.36941295e+02
  1.02787100e+03  1.20516988e+03 -2.22825449e+03 -1.63108109e+02
 -1.93692511e+03  1.22569814e+03  1.23808298e+02  4.72573795e+02
  4.96533218e+02 -7.04682077e+03  1.55099319e+04  3.56339360e+03
  7.55807962e-02 -3.89066391e-01 -4.42882499e-01  1.68034915e+00
  3.90671659e-01 -3.08993424e+01  2.39443829e+00 -7.10648772e+03
  1.01903054e+02  1.34456588e+02  3.11750608e+02  2.00839338e+03
 -3.57657809e+02  2.53270531e+00  4.40083476e+00  5.71181878e+00
  1.09469245e+02  9.08858560e+01 -1.00471844e+02  5.06134181e+01
 -6.14052028e+01  4.68859401e+02  5.74400427e+00  5.97438340e+01
  1.18554069e+02  4.65439374e+02 -6.34181598e+02 -2.07449040e+02
 -1.83868737e+07 -1.15458809e+05  3.42026499e+05  4.49965037e+05
  9.52731974e+06  8.42713414e+05 -2.24830795e+03 -5.71017957e+03
  5.33792425e+02  1.12692824e+05 -4.72503402e+04 -1.44108304e+03
 -5.81614111e+03 -6.35527070e+04 -3.66144453e+04 -2.42495863e+03
 -1.23945831e+05 -4.80604353e+04 -1.90819703e+06 -9.43293273e+04
 -1.61541853e+03  2.65067724e+01 -5.20296411e+02 -1.21151089e+02
  3.56801664e+03 -1.94034395e+03  5.69102153e+03 -1.48269485e+03
 -7.07258504e+03 -9.18615720e+03 -2.69878491e+02 -3.45017096e+02
 -2.06197391e+03 -6.41935986e+04 -3.09216016e+04 -1.96880689e+02
  2.82854674e+04  2.03794783e+03  7.60856737e+04  2.47139366e+04
 -9.41662089e+01  5.38651096e+03  3.13506290e+03 -2.50496808e+05
  7.62518587e+04  4.14432491e+04 -5.12943362e+01  3.79033292e+02
  3.03847297e+02 -3.81736421e+04 -9.28490250e+03  6.98211937e+03
 -2.18554868e+05  1.89872215e+05  9.16934435e+04 -1.39861639e+03]
trainr2: 0.8068315039380518
cv: 0.7952683792627692
Test r2: 0.7794904514743992